-- Initial PostgreSQL schema for Supabase.
-- Generated from financeiro/database.py, preserving the app's custom users model.

begin;

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null unique,
    password_hash text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.sessions (
    token text primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    created_at timestamptz not null default now()
);

create table if not exists public.password_resets (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    token_hash text not null,
    expires_at timestamptz not null,
    used_at timestamptz,
    created_at timestamptz not null default now()
);

create table if not exists public.auth_attempts (
    id bigint generated by default as identity primary key,
    action text not null,
    identifier text not null,
    attempt_count integer not null default 0 check (attempt_count >= 0),
    locked_until timestamptz,
    last_attempt_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (action, identifier)
);

create table if not exists public.checking_accounts (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    name text not null,
    bank_name text not null,
    branch text,
    account_number text,
    account_type text not null default 'liquidity' check (account_type in ('liquidity', 'wallet', 'investment')),
    currency text not null default 'BRL',
    initial_balance_cents bigint not null default 0,
    current_balance_cents bigint not null default 0,
    notes text,
    archived_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.credit_cards (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    name text not null,
    issuer text not null,
    network text,
    currency text not null default 'BRL',
    limit_cents bigint not null check (limit_cents > 0),
    closing_day integer not null check (closing_day between 1 and 31),
    due_day integer not null check (due_day between 1 and 31),
    preferred_payment_account_id bigint references public.checking_accounts(id),
    notes text,
    archived_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, name)
);

create table if not exists public.categories (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    name text not null,
    group_type text not null default 'expense' check (group_type in ('income', 'expense', 'investment')),
    created_at timestamptz not null default now(),
    unique (user_id, group_type, name)
);

create table if not exists public.subcategories (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    category_id bigint not null references public.categories(id) on delete cascade,
    name text not null,
    created_at timestamptz not null default now(),
    unique (category_id, name)
);

create table if not exists public.tags (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    name text not null,
    created_at timestamptz not null default now(),
    unique (user_id, name)
);

create table if not exists public.transactions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    type text not null check (type in ('income', 'expense', 'transfer', 'investment')),
    description text not null,
    amount_cents bigint not null check (amount_cents > 0),
    destination_amount_cents bigint not null default 0 check (destination_amount_cents >= 0),
    exchange_rate_micros bigint not null default 1000000 check (exchange_rate_micros > 0),
    transfer_exchange_rate_micros bigint not null default 0 check (transfer_exchange_rate_micros >= 0),
    amount_brl_cents bigint not null default 0 check (amount_brl_cents >= 0),
    date date not null,
    account_id bigint not null references public.checking_accounts(id),
    destination_account_id bigint references public.checking_accounts(id),
    category_id bigint references public.categories(id),
    subcategory_id bigint references public.subcategories(id),
    tag_id bigint references public.tags(id),
    series_id text,
    series_kind text not null default 'single',
    installment_index integer,
    installment_count integer,
    recurrence_frequency text,
    reconciled_at timestamptz,
    notes text,
    archived_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.credit_card_transactions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    credit_card_id bigint not null references public.credit_cards(id) on delete cascade,
    type text not null check (type in ('income', 'expense')),
    description text not null,
    amount_cents bigint not null check (amount_cents > 0),
    date date not null,
    invoice_month text not null,
    series_id text,
    series_kind text not null default 'single',
    installment_index integer,
    installment_count integer,
    recurrence_frequency text,
    category_id bigint references public.categories(id),
    subcategory_id bigint references public.subcategories(id),
    reconciled_at timestamptz,
    notes text,
    archived_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.credit_card_payments (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    credit_card_id bigint not null references public.credit_cards(id) on delete cascade,
    invoice_month text not null,
    account_id bigint not null references public.checking_accounts(id),
    transaction_id bigint not null references public.transactions(id),
    payment_date date not null,
    amount_cents bigint not null check (amount_cents > 0),
    notes text,
    created_at timestamptz not null default now(),
    unique (user_id, credit_card_id, invoice_month)
);

create table if not exists public.investment_operations (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    transaction_id bigint not null references public.transactions(id) on delete cascade,
    account_id bigint not null references public.checking_accounts(id) on delete cascade,
    asset_type text not null default 'other',
    asset_identifier text,
    asset_name text,
    cnpj text,
    quantity_micros bigint not null default 0 check (quantity_micros >= 0),
    unit_price_cents bigint not null default 0 check (unit_price_cents >= 0),
    invested_amount_cents bigint not null default 0 check (invested_amount_cents >= 0),
    brokerage_fee_cents bigint not null default 0 check (brokerage_fee_cents >= 0),
    exchange_fee_cents bigint not null default 0 check (exchange_fee_cents >= 0),
    tax_cents bigint not null default 0 check (tax_cents >= 0),
    other_costs_cents bigint not null default 0 check (other_costs_cents >= 0),
    fixed_income_mode text,
    fixed_income_indexer text,
    fixed_income_rate_micros bigint not null default 0 check (fixed_income_rate_micros >= 0),
    fixed_income_maturity_date date,
    savings_anniversaries_json jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (transaction_id)
);

create table if not exists public.investment_opening_positions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    account_id bigint not null references public.checking_accounts(id) on delete cascade,
    asset_type text not null default 'other',
    asset_identifier text,
    asset_name text,
    cnpj text,
    acquisition_date date not null,
    quantity_micros bigint not null default 0 check (quantity_micros >= 0),
    unit_price_cents bigint not null default 0 check (unit_price_cents >= 0),
    total_cost_cents bigint not null check (total_cost_cents > 0),
    exchange_rate_micros bigint not null default 1000000 check (exchange_rate_micros > 0),
    fixed_income_mode text,
    fixed_income_indexer text,
    fixed_income_rate_micros bigint not null default 0 check (fixed_income_rate_micros >= 0),
    fixed_income_maturity_date date,
    apply_tax_estimate boolean not null default false,
    savings_anniversaries_json jsonb,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.investment_redemptions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    account_id bigint not null references public.checking_accounts(id) on delete cascade,
    transaction_id bigint references public.transactions(id) on delete set null,
    source_type text not null check (source_type in ('operation', 'opening')),
    source_id bigint not null,
    redeemed_value_cents bigint not null check (redeemed_value_cents > 0),
    redeemed_cost_cents bigint not null check (redeemed_cost_cents >= 0),
    redeemed_quantity_micros bigint not null default 0 check (redeemed_quantity_micros >= 0),
    date date not null,
    notes text,
    created_at timestamptz not null default now()
);

create table if not exists public.investment_value_overrides (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    account_id bigint not null references public.checking_accounts(id) on delete cascade,
    asset_type text not null default 'other',
    asset_identifier text not null default '',
    asset_name text not null default '',
    cnpj text not null default '',
    fixed_income_indexer text not null default '',
    fixed_income_maturity_date text not null default '',
    current_value_cents bigint not null check (current_value_cents >= 0),
    quote_date date not null,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (
        user_id, account_id, asset_type, asset_identifier, asset_name,
        cnpj, fixed_income_indexer, fixed_income_maturity_date
    )
);

create table if not exists public.investment_closed_positions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    account_id bigint not null references public.checking_accounts(id) on delete cascade,
    currency text not null,
    asset_type text not null default 'other',
    asset_identifier text not null default '',
    asset_name text not null default '',
    cnpj text not null default '',
    fixed_income_indexer text not null default '',
    fixed_income_maturity_date text not null default '',
    closed_at date not null,
    source_count integer not null default 0 check (source_count >= 0),
    quantity_micros bigint not null default 0 check (quantity_micros >= 0),
    total_cost_cents bigint not null default 0 check (total_cost_cents >= 0),
    total_cost_brl_cents bigint not null default 0 check (total_cost_brl_cents >= 0),
    closing_value_cents bigint not null default 0 check (closing_value_cents >= 0),
    closing_value_brl_cents bigint not null default 0 check (closing_value_brl_cents >= 0),
    result_brl_cents bigint not null default 0,
    result_percent_micros bigint not null default 0,
    first_operation_date date,
    last_operation_date date,
    quote_source text,
    notes text,
    position_json jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (
        user_id, account_id, asset_type, asset_identifier, asset_name,
        cnpj, fixed_income_indexer, fixed_income_maturity_date, closed_at
    )
);

create table if not exists public.transaction_tags (
    transaction_id bigint not null references public.transactions(id) on delete cascade,
    tag_id bigint not null references public.tags(id) on delete cascade,
    primary key (transaction_id, tag_id)
);

create table if not exists public.credit_card_transaction_tags (
    credit_card_transaction_id bigint not null references public.credit_card_transactions(id) on delete cascade,
    tag_id bigint not null references public.tags(id) on delete cascade,
    primary key (credit_card_transaction_id, tag_id)
);

create table if not exists public.spending_limits (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    month text not null,
    category_id bigint not null references public.categories(id) on delete cascade,
    subcategory_id bigint references public.subcategories(id) on delete cascade,
    limit_amount_cents bigint not null check (limit_amount_cents > 0),
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.quote_cache (
    cache_key text primary key,
    payload_json jsonb not null,
    expires_at timestamptz not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists idx_spending_limits_category
    on public.spending_limits (user_id, month, category_id)
    where subcategory_id is null;

create unique index if not exists idx_spending_limits_subcategory
    on public.spending_limits (user_id, month, category_id, subcategory_id)
    where subcategory_id is not null;

create index if not exists idx_transactions_user_date
    on public.transactions (user_id, date);

create index if not exists idx_transactions_account
    on public.transactions (account_id);

create index if not exists idx_transactions_user_account_date
    on public.transactions (user_id, account_id, date);

create index if not exists idx_transactions_user_destination_date
    on public.transactions (user_id, destination_account_id, date);

create index if not exists idx_transactions_user_series_date
    on public.transactions (user_id, series_id, date);

create index if not exists idx_credit_card_transactions_card_month
    on public.credit_card_transactions (credit_card_id, invoice_month);

create index if not exists idx_credit_card_transactions_user_card_invoice_date
    on public.credit_card_transactions (user_id, credit_card_id, invoice_month, date);

create index if not exists idx_credit_card_transactions_user_invoice_date
    on public.credit_card_transactions (user_id, invoice_month, date);

create index if not exists idx_credit_card_transactions_user_series_invoice_date
    on public.credit_card_transactions (user_id, series_id, invoice_month, date);

create index if not exists idx_credit_card_payments_user_card_invoice
    on public.credit_card_payments (user_id, credit_card_id, invoice_month);

create index if not exists idx_credit_card_payments_user_date
    on public.credit_card_payments (user_id, payment_date);

create index if not exists idx_investment_operations_user
    on public.investment_operations (user_id, account_id, asset_type);

create index if not exists idx_investment_opening_positions_user
    on public.investment_opening_positions (user_id, account_id, asset_type);

create index if not exists idx_investment_redemptions_source
    on public.investment_redemptions (user_id, source_type, source_id);

create index if not exists idx_investment_value_overrides_user
    on public.investment_value_overrides (user_id, account_id, asset_type);

create index if not exists idx_investment_closed_positions_user
    on public.investment_closed_positions (user_id, account_id, asset_type, closed_at);

create index if not exists idx_subcategories_category
    on public.subcategories (category_id);

create index if not exists idx_transaction_tags_tag
    on public.transaction_tags (tag_id);

create index if not exists idx_credit_card_transaction_tags_tag
    on public.credit_card_transaction_tags (tag_id);

create index if not exists idx_password_resets_token
    on public.password_resets (token_hash, used_at, expires_at);

create index if not exists idx_auth_attempts_locked_until
    on public.auth_attempts (locked_until);

create index if not exists idx_quote_cache_expires_at
    on public.quote_cache (expires_at);

commit;
